fix: Shorten the time before API call
ddev/github-action-add-on-test pull request #31
Opened 2024-05-17 15:52 UTC by rfay

The current 55 day timeout before we hit the API seems to be a little long, as GitHub warns before 55 days. We can shorten it, here to 45.

But I'm not sure why we don't just use `1` here instead, not sure it would do any harm to hit the API daily.

2024-05-18 01:35 UTC, julienloizelet commented
Thanks for this PR.

I'd rather wait for [answers] (https://github.com/gautamkrishnar/keepalive-workflow/issues/36#issuecomment-2118546603) on this `time_elapsed` value.

In the end, I think we could set `"0"` as the default entry (this should make one call each time).

2024-05-18 17:53 UTC, gautamkrishnar commented
Thanks a lot for the PR and issue @rfay. Thanks for debugging. @julienloizelet 👍🏻. Looks good to me. Some more docs changes are required, i will make those myself.

2024-05-20 02:44 UTC, julienloizelet commented
@rfay ,
so now that we have all the answers, we have to decide.
Should we keep `"45"` in this PR or should we set `"0"` ?
In my opinion, `"0"` is a good move (if an user want to change, he still can as it is a configurable input).

With `"0"`, the api call will be done on every run.

2024-05-20 13:36 UTC, rfay commented
0 seems OK to me.

2024-05-20 23:43 UTC, julienloizelet requested changes
As we discussed, we could set `"0"` here, as a default value.

To be consistent with [keepalive original workflow](https://github.com/gautamkrishnar/keepalive-workflow), we should set the string `"0"` (and not the number `0`) because the original workflow expects a string as input.

(In my opinion, it was an already an error to set 55 and not "55" as default value).

2024-05-21 01:32 UTC, rfay commented on action.yaml
> +    default: 45
```suggestion
    default: "0"
```

2024-05-21 02:29 UTC, julienloizelet approved these changes
Thanks.

I will merge and make a new release asap (tomorrow, I guess)

2024-05-22 01:20 UTC, merged

2024-05-23 19:43 UTC, rfay commented
I'm not sure, but I think this may not have worked out right. I'm seeing test failures on stable (not latest) in a couple of repos, where the tests have obviously succeeded:

* https://github.com/justafish/ddev-drupal-core-dev/actions/runs/9213831558/job/25348604861?pr=33
* https://github.com/ddev/ddev-solr/actions/runs/9204758550

2024-05-24 00:22 UTC, julienloizelet commented
> I'm not sure, but I think this may not have worked out right. I'm seeing test failures on stable (not latest) in a couple of repos, where the tests have obviously succeeded:
> 
>     * https://github.com/justafish/ddev-drupal-core-dev/actions/runs/9213831558/job/25348604861?pr=33
> 
>     * https://github.com/ddev/ddev-solr/actions/runs/9204758550

Very strange, indeed: it appears to works well for most of the repos.

I've tried a couple of tests and all was successful.

For the solr repo, there is a permission issue; maybe it can explain the error.

For the ddev-drupal-core-dev repo, there is no obvious problem: I suspect a branch protection rule, or action permission settings, but, at least, there should be a more explicit error message in this case.

I'll ask @gautamkrishnar if he has any idea what might be the root cause.

2024-05-24 00:31 UTC, julienloizelet commented
I've created an issue : https://github.com/gautamkrishnar/keepalive-workflow/issues/42

Thanks