feat(*): Add test_command input and exclude release tagged tests for pull request
ddev/github-action-add-on-test pull request #34
Opened 2024-09-30 09:11 UTC by julienloizelet

## The Issue

Fixes #30 

## How This PR Solves The Issue

- By default, the test command launched on pull request workflow will be `bats tests --filter-tags !release`

With this, if the add-on test is tagged with the "release" tag, it won't be executed on pull request workflow: 

```
# bats test_tags=release
@test "install from release" {
...
...
}
```

- On other workflow ("schedule", "push", etc.), the test command will be, by default,  as before : `bats tests`

- If an add-on maintainer needs to pass a customized test command, there is a new available string input `test_command`.
When the `test_command` input is not empty, it will be used to run the test.

## Manual Testing Instructions

To test the final behavior, you can use my forked action and points to the last commit: 

```
steps:
      - uses: julienloizelet/ddev-add-on-test@b6b8c765ddba5fa511c2f9284e818d7fa3230f27
      with: 
          ...
```

### How to test

1) Backward compatibility : Create a pull request on your add-on: If you have no "release" tagged test, all test should be run as before

2) Exclude "release" test: Tag a test with the "release" tag. This test should not be executed on PR workflow.

3) Customized test_command: Use the `test_command` input to see if your customized test command is launched.

4) backward compatibility (hard to test: you can modify the tests.yml workflow to be triggered during a push on a testing branch that contains the new action). Ensure that the launched command, for a non pull request workflow, is as before (`bats tests`) and that all tests are runned.

2024-09-30 10:37 UTC, stasadev requested changes
Thank you @julienloizelet, I tested it with `julienloizelet/ddev-add-on-test@b6b8c765ddba5fa511c2f9284e818d7fa3230f27` on https://github.com/stasadev/ddev-redis and it works perfectly.

I only have a small suggestion.

2024-09-30 16:37 UTC, rfay commented
Awesome initiative, thanks!

2024-10-01 00:12 UTC, julienloizelet commented on action.yaml
> +        set +H
Thanks !

I've updated the code accordingly.

Should be testable with `julienloizelet/ddev-add-on-test@b9d39a4e18193bf3cb15f0ba109edb6f00d88eb5`

2024-10-01 10:09 UTC, stasadev approved these changes
I checked again, everything works as it should, thank you!

2024-10-01 23:43 UTC, merged

2024-10-02 00:11 UTC, rfay commented
What a great improvement, thanks!